# Generated by Django 3.2.24 on 2024-02-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_biographie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biographie',
        ),
    ]
