# Generated by Django 4.2.11 on 2024-03-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_actualite'),
    ]

    operations = [
        migrations.CreateModel(
            name='rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'Rubriques publications',
            },
        ),
    ]
