# Generated by Django 4.2.11 on 2024-03-09 13:49

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('core', '0010_rubrique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubrique',
            options={'verbose_name': 'Rubriques publication'},
        ),
        migrations.CreateModel(
            name='Conjoncture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('source', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(verbose_name='url')),
                ('intro', models.TextField(verbose_name="Texte d'introduction")),
                ('document', models.FileField(null=True, upload_to='media/')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Conjoncture',
                'ordering': ['-date_added'],
            },
        ),
    ]
